### ISSUE TITLE
connection?

### ISSUE THREAD

**Issue by ehartford** [tsyd/proxy-tamper#3]
I can't see the http connection object?

I'd like to respond to remoteAddress ip range, but I do not have access to the ip address in the request object.

I expected to see a request.connection.remoteAddress but I did not see one.

example:

```javascript
var proxy_tamper = require("proxy-tamper");
var proxy = proxy_tamper.start({port: 8000});
proxy.tamper("", function(request) {
  console.log(request.connection.remoteAddress);
});
```

(throws exception there is no "connection" in "request")

**Comment by tsyd** [comment]
Fixed in 3756a076a26bf5d30dc762857ca71afdab473331.
