### ISSUE TITLE
Double URLs?

### ISSUE THREAD

**Issue by dandart** [tsyd/proxy-tamper#7]
var proxy = require('./lib/proxy-tamper').start({ port: 8080 });

proxy.tamper(/www\.bob\.co\.uk\/$/, function(request) {
    console.log('requesting');
    delete request.headers['accept-encoding'];
    request.onResponse(function(response) {
        console.log('tampering');
        response.body = response.body.replace(/<head>/, '<head>things');
        response.headers['x-tampered-by'] = 'dan';
        response.complete();
    });
});

This forwards to http://www.bob.co.ukhttp/www.bob.co.uk...Can anyone help?

**Comment by tsyd** [comment]
@dandart: Which browser or HTTP client are you using to connect to the proxy?

Using the example that you provided:

```javascript
var proxy = require('./lib/proxy-tamper').start({port: 8080});

proxy.tamper(/www.bob.co.uk\/$/, function(request) {
  console.log('requesting');
  delete request.headers['accept-encoding'];

  request.onResponse(function(response) {
    console.log('tampering');
    response.body = response.body.replace(/.*/g, 'things');
    response.headers['x-tampered-by'] = 'dan';
    response.complete();
  });
});
```

Here's the output of running `curl`:

```
curl -v --proxy http://localhost:8080 http://www.bob.co.uk
* Rebuilt URL to: http://www.bob.co.uk/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET http://www.bob.co.uk/ HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.bob.co.uk
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< date: Tue, 14 Apr 2015 23:24:44 GMT
* Server Apache/2.2.16 is not blacklisted
< server: Apache/2.2.16
< vary: Accept-Encoding
< content-length: 455
< content-type: text/html;charset=UTF-8
< x-tampered-by: dan
< Connection: keep-alive
< 
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
thingsthings
```

**Comment by dandart** [comment]
Well, Chrome is screwing up with it then I'd guess...

**Comment by dandart** [comment]
Sorry - obfuscation was getting in the way... Here's the request I'm making

**Comment by tsyd** [comment]
Hi @dandart. The problem was that the proxy was sending an incorrect path in the HTTP request. It was including the the HTTP scheme and hostname in the path which most servers simply ignore, but www.hellou.co.uk did not. Let me know if you run into any other issues and thanks for reporting this!

**Comment by dandart** [comment]
Thanks will try that again

**Comment by dandart** [comment]
Cheers - haven't had any more problems with it since
